from __future__ import annotations

import html
import importlib
from pathlib import Path

import pandas as pd
import streamlit as st

from src.agents.estimator_agent import run_estimator
from src.agents.rfi_change_order_agent import answer_rfi_change_order
from src.agents.voice_agent import handle_voice_question
from src.services.document_loader import load_project_documents
import src.services.ollama_service as ollama_service_module
from src.services.vector_store_service import rebuild_index
from src.utils.config import DATA_DIR, DEFAULT_MODEL, MODEL_OPTIONS, PROJECT_ALIASES, PROJECTS

ollama_service_module = importlib.reload(ollama_service_module)
OllamaService = ollama_service_module.OllamaService

st.set_page_config(page_title="Electrical Project Intelligence Copilot", layout="wide")

st.markdown(
    """
    <style>
    .answer-box {
        font-size: 1rem;
        line-height: 1.55;
        white-space: pre-wrap;
    }
    .answer-box * {
        font-size: 1rem !important;
        line-height: 1.55 !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

EXAMPLES = {
    "school": [
        "Which panel serves the 3rd floor HVAC system?",
        "What lighting changes were requested for the cafeteria?",
        "Which RFIs are still unresolved?",
        "Generate a material takeoff for emergency lighting.",
        "Explain the classroom wiring plan to a field technician.",
    ],
    "hospital": [
        "Which panel supports the operating room isolated power system?",
        "What circuits are connected to emergency backup power?",
        "What changed in the imaging wing backup power change order?",
        "Generate an estimate for critical care room electrical work.",
        "Explain the generator/ATS setup in simple field language.",
    ],
    "food_mart": [
        "Which panel feeds the walk-in freezer?",
        "What wire and conduit are required for exterior signage?",
        "What changed in the latest signage change order?",
        "Generate a material takeoff for refrigeration power.",
        "Explain the POS low-voltage wiring plan to a technician.",
    ],
}


def list_files(project_id: str) -> pd.DataFrame:
    rows = []
    for path in sorted((DATA_DIR / project_id).rglob("*")):
        if path.is_file():
            rows.append({"File": str(path.relative_to(DATA_DIR / project_id)), "Size KB": round(path.stat().st_size / 1024, 1)})
    return pd.DataFrame(rows)


def show_sources(sources: list[dict]) -> None:
    if not sources:
        st.info("No sources returned.")
        return
    st.dataframe(pd.DataFrame(sources), use_container_width=True, hide_index=True)


def show_answer(result: dict) -> None:
    stale_fallback = "Ollama is not running, so this grounded extractive answer is based on retrieved project documents"
    if result.get("used_llm"):
        st.caption("Generated by local Ollama from retrieved project documents.")
    elif stale_fallback in result.get("answer", ""):
        result["answer"] = (
            "The app received an old fallback answer from a stale Streamlit import. "
            "Restart Streamlit with Ctrl+C and run `streamlit run app.py` again."
        )
        st.caption("Stale fallback response blocked.")
    else:
        st.caption("Ollama did not return a completed response.")
    st.markdown(f"<div class='answer-box'>{html.escape(result['answer'])}</div>", unsafe_allow_html=True)


with st.sidebar:
    st.title("Electrical Copilot")
    project_label = st.selectbox("Project", ["School", "Hospital", "Food Mart"])
    project_id = PROJECT_ALIASES[project_label]
    probe = OllamaService(DEFAULT_MODEL)
    installed_models = probe.list_models()
    model_options = installed_models or MODEL_OPTIONS
    preferred_model = next((name for name in model_options if name.startswith(DEFAULT_MODEL)), model_options[0])
    model = st.selectbox("Model", model_options, index=model_options.index(preferred_model))
    mode = st.selectbox(
        "Mode",
        ["Project Copilot", "Estimator Assistant", "Field Technician Assistant", "RFI / Change Order Assistant"],
    )
    if st.button("Rebuild local index", use_container_width=True):
        with st.spinner("Rebuilding local vector index..."):
            st.success(rebuild_index())
    show_files = st.checkbox("Show dataset files")
    ollama = OllamaService(model)
    if ollama.is_available():
        st.success(f"Ollama is running. Using `{model}`.")
    else:
        st.warning(f"Ollama is not reachable. Start it with `ollama serve` and make sure `{model}` is pulled.")
    if st.button("Test Ollama", use_container_width=True):
        with st.spinner("Waiting for Ollama..."):
            test_answer = ollama.generate("Reply with exactly: Ollama connected.")
        st.code(test_answer)

st.title("Electrical Project Intelligence Copilot")
st.caption("Local-first RAG, estimating, RFI/change-order review, and technician voice support for electrical contractors.")

if show_files:
    st.subheader(f"{project_label} Dataset Files")
    st.dataframe(list_files(project_id), use_container_width=True, hide_index=True)

tabs = st.tabs(["Chat Copilot", "Estimator", "Voice Assistant", "Project Documents", "RFIs & Change Orders", "Demo Script"])

with tabs[0]:
    st.subheader("Project-Specific Chat")
    cols = st.columns(5)
    for idx, question in enumerate(EXAMPLES[project_id]):
        if cols[idx].button(question, key=f"example_{idx}", use_container_width=True):
            st.session_state["chat_question"] = question
    question = st.chat_input("Ask about the selected electrical project")
    question = question or st.session_state.get("chat_question", "")
    if question:
        with st.spinner("Searching local documents..."):
            import src.agents.supervisor_agent as supervisor_agent_module

            supervisor_agent_module = importlib.reload(supervisor_agent_module)
            run_supervisor = supervisor_agent_module.run_supervisor
            result = run_supervisor(project_id, question, mode, model)
        show_answer(result)
        if "estimate" in result:
            st.dataframe(result["estimate"]["table"], use_container_width=True, hide_index=True)
        st.write("Route:", result.get("route", "retrieval"))
        st.write("Sources")
        show_sources(result.get("sources", []))
        st.session_state["chat_question"] = ""

with tabs[1]:
    st.subheader("AI Estimator Assistant")
    category = st.selectbox("Optional category filter", ["All", "Panels", "Lighting", "Emergency lighting", "Conduit", "Wire", "Fire alarm", "Low voltage", "HVAC", "Refrigeration", "Signage"])
    if st.button("Generate Estimate", type="primary"):
        filter_value = None if category == "All" else category
        result = run_estimator(project_id, filter_value)
        summary = result["summary"]
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Material", f"${summary['material_total']:,.0f}")
        m2.metric("Labor Hours", f"{summary['labor_hours']:,.1f}")
        m3.metric("Labor", f"${summary['labor_cost']:,.0f}")
        m4.metric("Total", f"${summary['total_cost']:,.0f}")
        st.dataframe(result["table"], use_container_width=True, hide_index=True)
        st.write("Assumptions")
        st.write(summary["assumptions"])
        st.write("Missing Data Warnings")
        st.write(summary["missing_data_warnings"])
        st.download_button("Download estimate CSV", result["table"].to_csv(index=False), file_name=f"{project_id}_estimate.csv")

with tabs[2]:
    st.subheader("Field Technician Voice Assistant")
    st.caption("Use manual text for reliable demos. Audio upload is supported when local speech recognition dependencies are available.")
    manual = st.text_input("Manual transcript or field question", placeholder="Which panel feeds the walk-in freezer?")
    audio = st.file_uploader("Optional WAV audio question", type=["wav", "aiff", "flac"])
    speak = st.checkbox("Speak answer with local TTS")
    if st.button("Ask Field Assistant"):
        audio_path = None
        if audio:
            tmp = Path("local_db/voice_transcripts") / audio.name
            tmp.parent.mkdir(parents=True, exist_ok=True)
            tmp.write_bytes(audio.getvalue())
            audio_path = str(tmp)
        result = handle_voice_question(project_id, model, manual_text=manual, audio_path=audio_path, speak=speak)
        st.write("Transcript")
        st.info(result["transcript"])
        st.write("Answer")
        st.success(result["answer"])
        st.caption(result.get("tts_status", ""))
        show_sources(result.get("sources", []))

with tabs[3]:
    st.subheader("Project Documents")
    docs = load_project_documents(project_id)
    st.metric("Indexed chunks", len(docs))
    st.dataframe(list_files(project_id), use_container_width=True, hide_index=True)
    selected = st.selectbox("Preview file", [str(p.relative_to(DATA_DIR / project_id)) for p in sorted((DATA_DIR / project_id).rglob("*")) if p.is_file() and p.suffix.lower() in {".txt", ".md", ".csv", ".json"}])
    if selected:
        st.code((DATA_DIR / project_id / selected).read_text(encoding="utf-8")[:5000])

with tabs[4]:
    st.subheader("RFIs & Change Orders")
    default_q = "Summarize unresolved RFIs and change orders with cost or schedule impact."
    rfi_q = st.text_area("Question", default_q)
    if st.button("Analyze RFIs and Change Orders"):
        result = answer_rfi_change_order(project_id, rfi_q, model)
        show_answer(result)
        show_sources(result["sources"])

with tabs[5]:
    st.subheader("Interview Demo Script")
    demo_path = Path("DEMO_SCRIPT.md")
    if demo_path.exists():
        st.markdown(demo_path.read_text(encoding="utf-8"))
    else:
        st.info("DEMO_SCRIPT.md will appear here after setup.")
